### ISSUE TITLE
"tojson" breaks templating

### ISSUE THREAD

**Issue by ae-v** [alannix-lw/lacework-agent-ansible-role#6]
Hi,

encountering this issue:

TASK [alannix_lw.lacework_agent_ansible_role : generate config.json] ****************************************************************************************************************************************************************fatal: [server_a]: FAILED! => {"changed": false, "msg": "AnsibleError: template error while templating string: no filter named 'tojson'. String: \n{\n  \"tokens\": {\n    \"AccessToken\" : \"{{ lacework_accessToken }}\"\n  }\n  {%- if lacework_cmdAllow is defined or lacework_cmdDisallow is defined %},\n  \"cmdlinefilter\" : {\n    \"allow\" : \"{{ lacework_cmdAllow | default(\"*\") }}\",\n    \"disallow\" : \"{{ lacework_cmdDisallow | default(\"\") }}\"\n  }\n  {%- endif %}\n  {%- if lacework_fimFilePath is defined or lacework_fimFileIgnore is defined %},\n  \"fim\" : {\n    {%- if lacework_fimFilePath is defined %}\n    \"filepath\" : {{ lacework_fimFilePath | tojson }}\n    {%- endif %}\n    {%- if lacework_fimFilePath is defined and lacework_fimFileIgnore is defined %},{%- endif %}\n    {%- if lacework_fimFileIgnore is defined %}\n    \"fileignore\" : {{ lacework_fimFileIgnore | tojson }}\n    {%- endif %}\n  }\n  {%- endif %}\n  {%- if lacework_autoUpgrade is defined %},\n  \"AutoUpgrade\" : \"{{ lacework_autoUpgrade }}\"\n  {%- endif %}\n  {%- if lacework_checkfreq is defined %},\n  \"checkfreq\" : \"{{ lacework_checkfreq }}\"\n  {%- endif %}\n  {%- if lacework_cpuLimit is defined %},\n  \"cpulimit\" : \"{{ lacework_cpuLimit }}\"\n  {%- endif %}\n  {%- if lacework_dbSize is defined %},\n  \"DbSize\" : \"{{ lacework_dbSize }}\"\n  {%- endif %}\n  {%- if lacework_interfaceConnectionSize is defined %},\n  \"InterfaceConnectionSize\" : \"{{ lacework_interfaceConnectionSize }}\"\n  {%- endif %}\n  {%- if lacework_memLimit is defined %},\n  \"memlimit\" : \"{{ lacework_memLimit }}\"\n  {%- endif %}\n  {%- if lacework_perfMode is defined %},\n  \"perfmode\" : \"{{ lacework_perfMode }}\"\n  {%- endif %}\n  {%- if lacework_proxyUrl is defined %},\n  \"ProxyUrl\" : \"{{ lacework_proxyUrl }}\"\n  {%- endif %}\n  {%- if lacework_tags is defined %},\n  \"Tags\": {{ lacework_tags |tojson }}\n  {%- endif %}\n}\n"}

Please consider replacing "tojson" in templates folder with "to_json" which is included in Ansible.
See https://github.com/ansible/ansible/issues/25381 which provides a few more details to the issue.

I used Ansible version 2.9.23.

I wonder why your role isn't referenced in the Lacework documentation. There is just an incomplete skeleton for Ansible users in the docs.

**Comment by alannix-lw** [comment]
Thanks for reporting this @ae-v !  I'm currently working on a PR to fix this, as well as a few other items, and add some automated integration testing.

**Comment by alannix-lw** [comment]
This should now be fixed with `v2.2.0` of the module.
